services:
  backend:
      build: ./backend
      volumes:
        - ./backend:/usr/src/app/
      ports:
        - "8000:8000"
      depends_on:
        - db
      env_file:
        - ./backend/config/.env

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/usr/src/app/
      - node_modules:/usr/src/app/node_modules/
    ports:
      - "5173:5173"
    env_file:
      - ./frontend/.env
    stdin_open: true

  db:
    image: postgres:16.4-bullseye
    volumes:
      - postgres_data:/var/lib/postgresql/braindead_data
    ports:
      - "5432:5432"
    env_file:
      - ./.env.db

volumes:
  postgres_data:
  node_modules: